---
- hosts: all
  vars:
    home: /Users/sulla # Your ~/
    src_home: /Users/sulla/src # Where your code lives
    applications: # .dmg, .app, .zip type applications via brew-cask
      - google-chrome
      - firefox
      - sublime-text
      - kitematic
      - terraform

  tasks:
    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - wget
        - ack
        - git

    - name: Install apps with brew-cask
      shell: brew cask install {{ item }}
      with_items: 
        - google-chrome
        - firefox
        - sublime-text
        - kitematic
        - terraform

    - name: Check for installed apps
      shell: brew cask list | grep {{ item }}
      register: installed_applications
      with_items: applications
      ignore_errors: true
